### PR TITLE
Feature 1

### PR DESCRIPTION
**Pull request by clouddevops65**

### CODE REVIEW

**Review by Vamsijani — COMMENTED** [review]
Please add extra stage for email notification

**Comment by clouddevops65** [comment]
> Please add extra stage for email notification

Sure

**Comment by Vamsijani** [comment]
> > Please add extra stage for email notification
> 
> Sure

Added email notification stage. Please from your side and let me know

**Review by Vamsijani — APPROVED** [review]
Approved

**Comment by clouddevops65** [comment]
Merged

**Pull request merged**
